# Generated by Django 4.2.29 on 2026-03-05 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackable_type', models.CharField(choices=[('lesson', 'Lesson'), ('video', 'Video')], max_length=20)),
                ('trackable_id', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'trackable_type'], name='accounts_co_user_id_e5c5b9_idx')],
                'unique_together': {('user', 'trackable_type', 'trackable_id')},
            },
        ),
    ]
