# Generated by Django 6.0.2 on 2026-02-05 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('scenario', models.CharField(choices=[('banking', 'Banking/Financial'), ('social_media', 'Social Media'), ('ecommerce', 'E-commerce'), ('government', 'Government'), ('corporate', 'Corporate'), ('prize', 'Prize/Lottery'), ('technical', 'Technical Support'), ('delivery', 'Delivery/Shipping')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('html_content', models.TextField(blank=True)),
                ('sender_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicators', models.ManyToManyField(blank=True, to='education.phishingindicator')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('user_clicked_link', models.BooleanField(default=False)),
                ('user_submitted_data', models.BooleanField(default=False)),
                ('user_reported', models.BooleanField(default=False)),
                ('user_identified_correctly', models.BooleanField(null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('indicators_identified', models.ManyToManyField(blank=True, to='education.phishingindicator')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulations.phishingtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('templates', models.ManyToManyField(to='simulations.phishingtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('correct_indicators', models.ManyToManyField(related_name='correct_in_simulations', to='education.phishingindicator')),
                ('missed_indicators', models.ManyToManyField(related_name='missed_in_simulations', to='education.phishingindicator')),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_feedback', to='simulations.simulation')),
            ],
        ),
    ]
